### ISSUE TITLE
Add function calling and add examples

### ISSUE THREAD

**Issue by FrancyJGLisboa** [elkronos/openai_api#2]
Any plans to implement Function Calling?

**Comment by elkronos** [comment]
Hey, could you elaborate on what you mean by "function calling"? Each script contains a series of functions which you can call. Are you asking if I am intending on making this repo into a package which is accessible via CRAN? If so, I have not decided. This repo was originally meant to be a place to share code with anyone interested and most of the functions were built to be stand alone. I would probably need to re-do the code for the assistants to all query the same API function. For instance, right now functions like `gpt_read` accesses the API with its own specialized API call, but I would need to make a more general call and integrate it into everything else. If there is enough interest I would consider it, but figured for now people could download the scripts that are of interest to them.
